commitizen:
  name: cz_conventional_commits
  tag_format: "v$version"
  version: 0.1.0
  version_scheme: "pep440"
  version_provider: "poetry"
  update_changelog_on_bump: true
  template: "docs/templates/changelog.j2"
  changelog_file: "docs/docs/changelog.md"
  release_notes_file: "docs/docs/release_notes.md"
